function f_withCompliance = processODE_withCompliance(v_Bx,v_By,v_Bz,omega_Bx,omega_By,omega_Bz,f_B_ox,f_B_oy,f_B_oz,mu_B_ox,mu_B_oy,mu_B_oz,f_B_cx,f_B_cy,f_B_cz,mu_B_cx,mu_B_cy,mu_B_cz,phi1,phi2,phi3,k_xx,k_yy,k_zz,c_xx,c_yy,c_zz,phi01,phi02,phi03,I_Bxx,I_Bxy,I_Bxz,I_Byy,I_Byz,I_Bzz,m,G_g1,G_g2,G_g3)
%PROCESSODE_WITHCOMPLIANCE
%    F_WITHCOMPLIANCE = PROCESSODE_WITHCOMPLIANCE(V_BX,V_BY,V_BZ,OMEGA_BX,OMEGA_BY,OMEGA_BZ,F_B_OX,F_B_OY,F_B_OZ,MU_B_OX,MU_B_OY,MU_B_OZ,F_B_CX,F_B_CY,F_B_CZ,MU_B_CX,MU_B_CY,MU_B_CZ,PHI1,PHI2,PHI3,K_XX,K_YY,K_ZZ,C_XX,C_YY,C_ZZ,PHI01,PHI02,PHI03,I_BXX,I_BXY,I_BXZ,I_BYY,I_BYZ,I_BZZ,M,G_G1,G_G2,G_G3)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    22-Oct-2015 10:35:22

t2 = cos(phi1);
t3 = sin(phi3);
t4 = cos(phi2);
t5 = cos(phi3);
t6 = sin(phi1);
t7 = 1.0./m;
t8 = sin(phi2);
t9 = I_Byz.^2;
t10 = I_Bxy.^2;
t11 = omega_By.^2;
t12 = I_Bxz.^2;
t13 = omega_Bx.^2;
t14 = omega_Bz.^2;
t15 = k_xx.^2;
t16 = c_xx.^2;
t17 = c_yy.^2;
t18 = c_zz.^2;
t19 = k_yy.^2;
t20 = k_zz.^2;
t21 = I_Bzz.^2;
t22 = I_Byy.^2;
t23 = I_Bxx.*t9;
t24 = I_Byy.*t12;
t25 = I_Bzz.*t10;
t29 = I_Bxx.*I_Byy.*I_Bzz;
t30 = I_Bxy.*I_Bxz.*I_Byz.*2.0;
t26 = t23+t24+t25-t29-t30;
t27 = 1.0./t26;
t28 = I_Bxx.^2;
t31 = t5.^2;
t32 = t3.^2;
t33 = t31+t32;
t34 = 1.0./t33;
t35 = 1.0./t8;
f_withCompliance = [-G_g1.*(t3.*t6-t2.*t4.*t5)+G_g2.*(t2.*t3+t4.*t5.*t6)+f_B_cx.*t7-f_B_ox.*t7-omega_By.*v_Bz+omega_Bz.*v_By-G_g3.*t5.*t8;-G_g1.*(t5.*t6+t2.*t3.*t4)+G_g2.*(t2.*t5-t3.*t4.*t6)+f_B_cy.*t7-f_B_oy.*t7+omega_Bx.*v_Bz-omega_Bz.*v_Bx+G_g3.*t3.*t8;G_g3.*t4+f_B_cz.*t7-f_B_oz.*t7-omega_Bx.*v_By+omega_By.*v_Bx+G_g1.*t2.*t8+G_g2.*t6.*t8;t27.*(mu_B_cx.*t9-mu_B_ox.*t9-I_Bxy.*I_Byz.*mu_B_cz+I_Bxy.*I_Bzz.*mu_B_cy+I_Bxz.*I_Byy.*mu_B_cz-I_Bxz.*I_Byz.*mu_B_cy-I_Byy.*I_Bzz.*mu_B_cx+I_Bxy.*I_Byz.*mu_B_oz-I_Bxy.*I_Bzz.*mu_B_oy-I_Bxz.*I_Byy.*mu_B_oz+I_Bxz.*I_Byz.*mu_B_oy+I_Byy.*I_Bzz.*mu_B_ox-I_Byz.*t9.*t11-I_Byz.*t10.*t11+I_Byz.*t9.*t14+I_Byz.*t10.*t13-I_Byz.*t12.*t13+I_Byz.*t12.*t14-omega_Bx.*t9.*t16+phi01.*t9.*t15-phi1.*t9.*t15+I_Bxy.*I_Bxz.*I_Byy.*t11-I_Bxy.*I_Bxz.*I_Byy.*t13+I_Bxy.*I_Bxz.*I_Bzz.*t13+I_Byy.*I_Byz.*I_Bzz.*t11-I_Bxy.*I_Bxz.*I_Bzz.*t14-I_Byy.*I_Byz.*I_Bzz.*t14+I_Byy.*I_Bzz.*omega_Bx.*t16-I_Bxy.*I_Bzz.*omega_By.*t17+I_Bxz.*I_Byz.*omega_By.*t17+I_Bxy.*I_Byz.*omega_Bz.*t18-I_Bxz.*I_Byy.*omega_Bz.*t18-I_Byy.*I_Bzz.*phi01.*t15+I_Byy.*I_Bzz.*phi1.*t15+I_Bxy.*I_Bzz.*phi02.*t19-I_Bxy.*I_Bzz.*phi2.*t19-I_Bxz.*I_Byz.*phi02.*t19+I_Bxz.*I_Byz.*phi2.*t19-I_Bxy.*I_Byz.*phi03.*t20+I_Bxy.*I_Byz.*phi3.*t20+I_Bxz.*I_Byy.*phi03.*t20-I_Bxz.*I_Byy.*phi3.*t20+I_Bxy.*omega_Bx.*omega_Bz.*t9.*2.0-I_Bxz.*omega_Bx.*omega_By.*t9.*2.0+I_Byy.*omega_By.*omega_Bz.*t9-I_Bzz.*omega_By.*omega_Bz.*t9+I_Byy.*omega_By.*omega_Bz.*t12-I_Bzz.*omega_By.*omega_Bz.*t10+I_Bxy.*omega_Bx.*omega_Bz.*t21-I_Bxz.*omega_Bx.*omega_By.*t22+I_Byy.*omega_By.*omega_Bz.*t21-I_Bzz.*omega_By.*omega_Bz.*t22-I_Bxx.*I_Bxy.*I_Byz.*omega_Bx.*omega_By+I_Bxx.*I_Bxz.*I_Byy.*omega_Bx.*omega_By-I_Bxx.*I_Bxy.*I_Bzz.*omega_Bx.*omega_Bz+I_Bxx.*I_Bxz.*I_Byz.*omega_Bx.*omega_Bz+I_Bxy.*I_Byy.*I_Byz.*omega_Bx.*omega_By-I_Bxy.*I_Byy.*I_Bzz.*omega_Bx.*omega_Bz+I_Bxy.*I_Byz.*I_Bzz.*omega_Bx.*omega_By-I_Bxz.*I_Byy.*I_Byz.*omega_Bx.*omega_Bz+I_Bxz.*I_Byy.*I_Bzz.*omega_Bx.*omega_By-I_Bxz.*I_Byz.*I_Bzz.*omega_Bx.*omega_Bz);t27.*(mu_B_cy.*t12-mu_B_oy.*t12+I_Bxx.*I_Byz.*mu_B_cz-I_Bxx.*I_Bzz.*mu_B_cy-I_Bxy.*I_Bxz.*mu_B_cz+I_Bxy.*I_Bzz.*mu_B_cx-I_Bxz.*I_Byz.*mu_B_cx-I_Bxx.*I_Byz.*mu_B_oz+I_Bxx.*I_Bzz.*mu_B_oy+I_Bxy.*I_Bxz.*mu_B_oz-I_Bxy.*I_Bzz.*mu_B_ox+I_Bxz.*I_Byz.*mu_B_ox+I_Bxz.*t9.*t11-I_Bxz.*t10.*t11-I_Bxz.*t9.*t14+I_Bxz.*t10.*t13+I_Bxz.*t12.*t13-I_Bxz.*t12.*t14-omega_By.*t12.*t17+phi02.*t12.*t19-phi2.*t12.*t19+I_Bxx.*I_Bxy.*I_Byz.*t11-I_Bxx.*I_Bxy.*I_Byz.*t13-I_Bxx.*I_Bxz.*I_Bzz.*t13-I_Bxy.*I_Byz.*I_Bzz.*t11+I_Bxx.*I_Bxz.*I_Bzz.*t14+I_Bxy.*I_Byz.*I_Bzz.*t14-I_Bxy.*I_Bzz.*omega_Bx.*t16+I_Bxz.*I_Byz.*omega_Bx.*t16+I_Bxx.*I_Bzz.*omega_By.*t17-I_Bxx.*I_Byz.*omega_Bz.*t18+I_Bxy.*I_Bxz.*omega_Bz.*t18+I_Bxy.*I_Bzz.*phi01.*t15-I_Bxy.*I_Bzz.*phi1.*t15-I_Bxz.*I_Byz.*phi01.*t15+I_Bxz.*I_Byz.*phi1.*t15-I_Bxx.*I_Bzz.*phi02.*t19+I_Bxx.*I_Bzz.*phi2.*t19+I_Bxx.*I_Byz.*phi03.*t20-I_Bxx.*I_Byz.*phi3.*t20-I_Bxy.*I_Bxz.*phi03.*t20+I_Bxy.*I_Bxz.*phi3.*t20-I_Bxx.*omega_Bx.*omega_Bz.*t9-I_Bxx.*omega_Bx.*omega_Bz.*t12-I_Bxy.*omega_By.*omega_Bz.*t12.*2.0+I_Byz.*omega_Bx.*omega_By.*t12.*2.0+I_Bzz.*omega_Bx.*omega_Bz.*t10+I_Bzz.*omega_Bx.*omega_Bz.*t12-I_Bxx.*omega_Bx.*omega_Bz.*t21-I_Bxy.*omega_By.*omega_Bz.*t21+I_Byz.*omega_Bx.*omega_By.*t28+I_Bzz.*omega_Bx.*omega_Bz.*t28-I_Bxx.*I_Bxy.*I_Bxz.*omega_Bx.*omega_By-I_Bxx.*I_Byy.*I_Byz.*omega_Bx.*omega_By+I_Bxy.*I_Bxz.*I_Byy.*omega_Bx.*omega_By+I_Bxx.*I_Bxy.*I_Bzz.*omega_By.*omega_Bz+I_Bxx.*I_Bxz.*I_Byz.*omega_By.*omega_Bz-I_Bxx.*I_Byz.*I_Bzz.*omega_Bx.*omega_By-I_Bxy.*I_Bxz.*I_Bzz.*omega_Bx.*omega_By+I_Bxy.*I_Byy.*I_Bzz.*omega_By.*omega_Bz-I_Bxz.*I_Byy.*I_Byz.*omega_By.*omega_Bz+I_Bxz.*I_Byz.*I_Bzz.*omega_By.*omega_Bz);t27.*(mu_B_cz.*t10-mu_B_oz.*t10-I_Bxx.*I_Byy.*mu_B_cz+I_Bxx.*I_Byz.*mu_B_cy-I_Bxy.*I_Bxz.*mu_B_cy-I_Bxy.*I_Byz.*mu_B_cx+I_Bxz.*I_Byy.*mu_B_cx+I_Bxx.*I_Byy.*mu_B_oz-I_Bxx.*I_Byz.*mu_B_oy+I_Bxy.*I_Bxz.*mu_B_oy+I_Bxy.*I_Byz.*mu_B_ox-I_Bxz.*I_Byy.*mu_B_ox+I_Bxy.*t9.*t11+I_Bxy.*t10.*t11-I_Bxy.*t9.*t14-I_Bxy.*t10.*t13-I_Bxy.*t12.*t13+I_Bxy.*t12.*t14-omega_Bz.*t10.*t18+phi03.*t10.*t20-phi3.*t10.*t20-I_Bxx.*I_Bxy.*I_Byy.*t11+I_Bxx.*I_Bxy.*I_Byy.*t13+I_Bxx.*I_Bxz.*I_Byz.*t13-I_Bxz.*I_Byy.*I_Byz.*t11-I_Bxx.*I_Bxz.*I_Byz.*t14+I_Bxz.*I_Byy.*I_Byz.*t14+I_Bxy.*I_Byz.*omega_Bx.*t16-I_Bxz.*I_Byy.*omega_Bx.*t16-I_Bxx.*I_Byz.*omega_By.*t17+I_Bxy.*I_Bxz.*omega_By.*t17+I_Bxx.*I_Byy.*omega_Bz.*t18-I_Bxy.*I_Byz.*phi01.*t15+I_Bxy.*I_Byz.*phi1.*t15+I_Bxz.*I_Byy.*phi01.*t15-I_Bxz.*I_Byy.*phi1.*t15+I_Bxx.*I_Byz.*phi02.*t19-I_Bxx.*I_Byz.*phi2.*t19-I_Bxy.*I_Bxz.*phi02.*t19+I_Bxy.*I_Bxz.*phi2.*t19-I_Bxx.*I_Byy.*phi03.*t20+I_Bxx.*I_Byy.*phi3.*t20+I_Bxx.*omega_Bx.*omega_By.*t9+I_Bxx.*omega_Bx.*omega_By.*t10-I_Byy.*omega_Bx.*omega_By.*t10+I_Bxz.*omega_By.*omega_Bz.*t10.*2.0-I_Byy.*omega_Bx.*omega_By.*t12-I_Byz.*omega_Bx.*omega_Bz.*t10.*2.0+I_Bxx.*omega_Bx.*omega_By.*t22+I_Bxz.*omega_By.*omega_Bz.*t22-I_Byy.*omega_Bx.*omega_By.*t28-I_Byz.*omega_Bx.*omega_Bz.*t28+I_Bxx.*I_Bxy.*I_Bxz.*omega_Bx.*omega_Bz-I_Bxx.*I_Bxy.*I_Byz.*omega_By.*omega_Bz-I_Bxx.*I_Bxz.*I_Byy.*omega_By.*omega_Bz+I_Bxx.*I_Byy.*I_Byz.*omega_Bx.*omega_Bz+I_Bxy.*I_Bxz.*I_Byy.*omega_Bx.*omega_Bz+I_Bxx.*I_Byz.*I_Bzz.*omega_Bx.*omega_Bz-I_Bxy.*I_Bxz.*I_Bzz.*omega_Bx.*omega_Bz-I_Bxy.*I_Byy.*I_Byz.*omega_By.*omega_Bz+I_Bxy.*I_Byz.*I_Bzz.*omega_By.*omega_Bz-I_Bxz.*I_Byy.*I_Bzz.*omega_By.*omega_Bz);0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;t34.*t35.*(omega_By.*t3+omega_Bx.*t5);-t34.*(omega_Bx.*t3-omega_By.*t5);-t34.*t35.*(omega_By.*t3.*t4+omega_Bx.*t4.*t5-omega_Bz.*t8.*t31-omega_Bz.*t8.*t32);0.0;0.0;0.0;0.0;0.0;0.0];
